services:
  bot:
    image: 192.168.1.50:5000/bot_image
    hostname: bot
  pg-master:
    image: 192.168.1.50:5000/db_image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: shurik_bot
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
    command: |
     postgres
      -c archive_mode=on
      -c archive_command='cp %p /var/pg_data/archive/%f'
      -c max_wal_senders=10
      -c wal_level=replica
      -c wal_log_hints=on
      -c max_replication_slots=10
      -c log_replication_commands=on
      -c log_timezone='Europe/Samara'
      -c log_statement=all
    ports:
      - 5432:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    shm_size: 1g

  pg-replica:
    image: 192.168.1.50:5000/db_repl_image
    shm_size: 1g
    environment:
      PGUSER: repl_user
      PGPASSWORD: P@ssw0rd
      PGHOST: pg-master
    command: |
      bash -c "
      rm -rf /var/lib/postgresql/data/* && pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot;
      chown -R postgres:postgres /var/lib/postgresql/data && chmod 0700 /var/lib/postgresql/data;
      su postgres -c postgres;
      "
    depends_on:
      - pg-master
    restart: always
    ports:
      - 5433:5432
